### ISSUE TITLE
关于关闭特定功能

### ISSUE THREAD

**Issue by MoeSoap** [Bluefissure/FFXIVBOT#1]
请问能否增加一个关闭特定功能的命令呢   比如关闭/cat命令和不接受@？群友天天复读有点频繁了

**Comment by Bluefissure** [comment]
如果你是普通用户可以![](https://i.loli.net/2018/07/10/5b44396b2778d.png)
如果你是管理员可以用/repeat_ban来进行复读姬禁言（

**Comment by MoeSoap** [comment]
这个/repeat_ban是禁言bot吗 不想让bot回应@和/cat

**Comment by Bluefissure** [comment]
禁言复读的人
不想让bot回应可以禁言bot或自己部署新的bot

**Comment by Bluefissure** [comment]
提供了通过/command关闭特定群功能的功能
