### ISSUE TITLE
感谢作者大大！粗略看了一下项目，有一点建议

### ISSUE THREAD

**Issue by ShigureNya** [Bluefissure/FFXIVBOT#3]
个人觉得django自带的orm关系映射比较方便，比起用sql做操作效率高一些_(:зゝ∠)_

**Comment by Bluefissure** [comment]
是用的orm啊……正式环境数据库是mysql的，只是上传到github的版本里的数据库配置留做默认了。
方便是的确方便，效率的话我也不清楚……感觉功能很强大但是我只是懂一点皮毛了（比如实现websocket原来是加载dwebsocket插件，之后才发现官方推了channels的实现方式（
但是生产环境的daphne却有点问题，现在的asgi服务器是用的[uvicorn](https://www.uvicorn.org/)
代码写的超级乱还都堆在一起，我自己都不想读（摔）。然后github的同步也很怠惰……今天下班看看哪里有修改再push一下……
