### ISSUE TITLE
Update dps to fflogs API v1

### ISSUE THREAD

**Issue by Bluefissure** [Bluefissure/FFXIVBOT#42]
It seems FFLogs is banning bots from scrawling the HTML, so we need to change the method of computing dps statistics to FFLogs API v1.

**Comment by Bluefissure** [comment]
It seems no metric statistics can be directly accessed from the API, so I decide to keep crawling the web page.
Maybe I'll add some cache methods to avoid the frequent access.

**Comment by CodeZWT** [comment]
抓取网页实际只需在请求头部加入Referer参数为"https://cn.fflogs.com/"即可，短期测试可用
