### ISSUE TITLE
WebSocket DISCONNECT

### ISSUE THREAD

**Issue by MYuuuuuu** [Bluefissure/FFXIVBOT#5]
挂一天之后ws就断开连接了，日志里全部是
[2018/09/21 03:06:10] WebSocket DISCONNECT /ws_event/ [193.112.70.193:52632]
[2018/09/21 03:06:15] WebSocket HANDSHAKING /ws_event/ [193.112.70.193:57354]
重启酷Q客户端后就可以再次连接。

**Comment by Bluefissure** [comment]
你的生产环境是如何搭建的？
两次log之间这段时间内是否有通过Event的ws连接上报消息？
如果是nginx转发ws连接，默认会在1分钟后断开连接，这个时间可以改长一些。
另外ws连接在一段时间内没有数据传输也会断掉，建议用心跳保持长连接。
另外如果只是自己搭建，不打算支持多个客户端建议使用[HTTP的通信模式](https://github.com/Bluefissure/FFXIVBOT/tree/be91c3fb3910479733db937f5f7f263dcef331a7)。

**Comment by MYuuuuuu** [comment]
增加心跳包解决了

**Comment by Bluefissure** [comment]
[最新](https://github.com/richardchien/coolq-http-api/releases)的http-api插件提供了[客户端心跳](https://github.com/richardchien/coolq-http-api/issues/121)的发起方式
