### ISSUE TITLE
Failed to open file 'FFXIV.sql', error: 2

### ISSUE THREAD

**Issue by snow-dream** [Bluefissure/FFXIVBOT#52]
跟着wiki一步步来的 到导入FFXIV.sql的时候报错 是哪里不对吗 看了下目录也没找都该sql文件

**Comment by Bluefissure** [comment]
不好意思，现在需要通过`python manage.py loaddata db/*.json`的方式导入数据
wiki相关文档随后更新

**Comment by snow-dream** [comment]
实际上 更新后的wiki数据导入章节依旧错误 (大概)

**Comment by Bluefissure** [comment]
> 实际上 更新后的wiki数据导入章节依旧错误 (大概)

具体是什么错误呢？
