### ISSUE TITLE
獭爹獭爹  能否开放一个獭獭图库的上传api

### ISSUE THREAD

**Issue by Lloml** [Bluefissure/FFXIVBOT#55]
自搭的獭窝也想同步到官方獭獭的图库 方便上传和获取更多的沙雕图

**Comment by Bluefissure** [comment]
上传基本不会提供API，因为图库的API是购买的，有限量。
但是可以定时导出图库中的部分图片，由于可能牵扯到各种问题只做了部分关键词的导出。
详见 https://github.com/Bluefissure/FFXIVBOT/tree/master/utils/image
