### ISSUE TITLE
sqlite3 database is locked

### ISSUE THREAD

**Issue by MYuuuuuu** [Bluefissure/FFXIVBOT#6]
注册群时候提示数据库被锁定，读取不受影响，抓取数据的脚本也可以正常运行

**Comment by Bluefissure** [comment]
建议使用MySQL等数据库，[详见文档](https://docs.djangoproject.com/en/2.0/ref/databases/)，sqlite的多线程操作可能存在[这个问题](https://www.sqlite.org/cvstrac/wiki?p=DatabaseIsLocked&1181909407)

**Comment by MYuuuuuu** [comment]
换成了MySQL后可以使用了
