### ISSUE TITLE
请求重新设置部分指令的权限或设立特别权限组

### ISSUE THREAD

**Issue by LittleNightmare** [Bluefissure/FFXIVBOT#73]
mirai机器人进群后，管理员也无法使用/group update。可能群主有权限，但群主经常不在。针对此使用情景，可能放开部分指令的权限，如/group update，或设立特别权限组是比较好的解决方案。

**Comment by Bluefissure** [comment]
https://github.com/Bluefissure/FFXIVBOT/commit/52ea1618fb726895fe5f8b33adf9fa648ed0054f
然而我没有测试mirai的插件能否正常获取群成员信息并响应 `get_group_member_list` 接口。

**Comment by LittleNightmare** [comment]
根据[cqhttp-mirai](https://github.com/yyuueexxiinngg/cqhttp-mirai)的readme，支持`GetGroupMemberList`，应该是可以用的。另外，在我一个测试用的群里（只有我和机器人），使用`/group update`后台没有报错，我认为应该会正常运行。
