### ISSUE TITLE
您好，我想知道FFLOGS部分是如何实现的。

### ISSUE THREAD

**Issue by ldiniiy** [Bluefissure/FFXIVBOT#8]
如果您能告诉我那个文件是相关代码，我可以自己去看。
如果您能简要讲讲，就更感激不尽了。

**Comment by Bluefissure** [comment]
https://github.com/Bluefissure/FFXIVBOT/blob/master/ffxivbot/handlers/QQCommand_dps.py#L13
看这个方法就行了，下面的都是业务逻辑
